cargo-features = ["profile-rustflags"]

[package]
name = "ABSENT"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ABSENT"
path = "ABSENT/main.rs"

[dependencies]
cc = "1.0" # used in future
capstone = "0.12.0"

once_cell = "1.17"
anyhow = "1.0"

winapi = { version = "0.3", features = [
    "memoryapi",
    "psapi",
    "tlhelp32",
    "winnt",
    "winbase",
    "processthreadsapi",
    "handleapi",
    "errhandlingapi",
    "sysinfoapi",
    "winuser"
] }

[build-dependencies]
cc = "1.0" # used in future

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
opt-level = "z"
debug = false
strip = "symbols"
overflow-checks = true
rustflags = ["-C", "link-arg=/GUARD:CF"] # does this exist?
