cargo-features = ["profile-rustflags"]

[package]
name = "ABSENT"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ABSENT"
path = "ABSENT/main.rs"

[dependencies]
cc = "1.0" # used in future
capstone = "0.12.0"

windows-sys = { version = "0.59", features = [

    "Win32_Foundation",

    "Win32_System_Diagnostics_Debug",
    "Win32_System_ProcessStatus",
    "Win32_System_LibraryLoader",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_Threading",
    "Win32_System_Memory",
    "Win32_System_SystemInformation",
    "Win32_System_SystemServices",
    "Win32_System_Console",

    "Win32_UI_WindowsAndMessaging",

]}

once_cell = "1.17"
anyhow = "1.0"

[build-dependencies]
cc = "1.0" # used in future

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
opt-level = "z"
debug = false
strip = "symbols"
overflow-checks = true
rustflags = ["-C", "link-arg=/GUARD:CF"] # does this exist?